<SpinnerOption>:
    size_hint: None, None
    size: 130, 40

<Button>:
    size_hint: (None, None)
    width: 130
    height: 40

<ToggleButton>:
    size_hint: (None, None)
    width: 130
    height: 40

<TextInput>:
    size_hint: (None, None)
    width: 130
    height: 30
    multiline: False

<PanelBoxLayout>:
    size_hint: (None, None)
    width: 1400
    height: 220

<SidebarBoxLayout>:
    size_hint_x: None
    width: 290
    padding: 20
    spacing: 15