name: dockerify
on:
  workflow_run:
    workflows:
      - deploy
    types:
      - completed
    branches:
      - master
      - develop
env:
  PROJECT_NAME: psyke-python
  WORKFLOW: dockerify
  RETRY_TIME: 5m
  MAX_RETRIES: 3
jobs:
  dockerify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Dockerify with Jupyter support
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERANAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0 # all history
          submodules: recursive

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Get Version
        id: get-version
        run: echo ::set-output name=version::$(python setup.py get_project_version | tail -n 1)

      - name: Create Docker Image
        run: ./.github/scripts/retry.sh "docker build -t pikalab/psyke:$PSYKE_VERSION --build-arg PSYKE_VERSION=$PSYKE_VERSION ."
        shell: bash
        env:
          PSYKE_VERSION: '${{ steps.get-version.outputs.version }}'

      - name: Push Image on Docker Hub
        run: docker push pikalab/psyke:${{ steps.get-version.outputs.version }}
